### ISSUE TITLE
Unacknowledged Pull Requests / Lack of Maintenance

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [knoxpo/dart_algolia#70]
I just noticed that after I created PR #67 one week ago, you went ahead and committed https://github.com/knoxpo/dart_algolia/commit/9e60161ac9db790b9cf84be276649d1ce9344454 without **any** notice. There has not been a single comment on any of the related PRs or issues this addresses.

Instead, you simply took the code from the PRs with minor adjustments and committed them yourself. This is IMO not an acceptable practice for an open source repo and I wish we could (together) improve maintenance on this repo!  
This is probably not really legal either considering copyright.

**Comment by nhathiwala** [comment]
@creativecreatorormaybenot I understand, your PR was left unattended, apologies, this was not intentional ( actually,  I didn't even look at your PR #67, just saw #56 and issues reported). There were few issues with the code in the PR and then I had few changes from my end in the snapshots and I just didn't have much time to coordinate (a real big set back from my side, agreed). However, I decided to go with faster way to process this which was to go with all my implementation and using some of suggested implementation. Apologies.

**Comment by creativecreatorormaybenot** [comment]
@nhathiwala Actually, you definitely saw my PR because you copied some of my code that had nothing to do with the features. I appreciate your reply nonetheless.

In the future, this should just be handled differently.
